CREATE TABLE IF NOT EXISTS `api_keys`
(
    `id`         int AUTO_INCREMENT,
    `key`        TEXT      NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`)
)

